<html>
<head>
  <head>
<body>
  <form action="{{url('addnew')}}" method="post" enctype="multipart/form-data">
    <input type="text" name="title" placeholder="title">
    <input type="text" name="channel_info" placeholder="title">
    <input type="text" name="max_participants" placeholder="participant(number)">
    <input type="file" name="images" placeholder="participant(number)">
    <input type="submit" value="Create">
  </form>
</body>
</html>
